In [1]:
import numpy as np


### Array 만들기

In [2]:
# List -> Array 만들기 
data1 = [6, 7.5, 8, 0, 1]


In [3]:
# numpy를 이용하여 1차원 배열로 변형하기
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
# 배열의 크기 확인
arr1.shape

(5,)

In [5]:
# 2차원 list 
data2 = [
  [1,2,3,4],
  [5,6,7,8]
  ]

In [6]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.shape


(2, 4)

In [8]:
#  0으로 구성된 1차원 array 생성 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
# 1로 구성된 1차원 array 생성 
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
# 특정숫자 (10)으로 구성된 1차원 array 생성
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [12]:
# 0으로 구성된 3행 5열 2차원 array 생성 
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# 특정숙자 (10)으로 구성된 3행 5열 2차원 배렬생성 
np.full((3,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [14]:
# 범위가 있는 Array 
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
# array 생성시 data type 정의 
arr3 = np.array(
  [1,2,3,4,5,6],
  dtype=np.int64
)

arr3

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [16]:
np.power(2, 16)


65536

In [18]:
# Data type을 변경
float_arr3 = arr3.astype(np.float64)
float_arr3

array([1., 2., 3., 4., 5., 6.])

## 연산

In [19]:
arr1 = np.array(
  (
    [1,2,3],
    [4,5,6]
  ), dtype=np.float64
)

arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
arr2 = np.array(
  (
    [7,8,9],
    [10,11,12]
  ), dtype=np.float64
)

arr2


array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [21]:
arr1 + arr2 

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [22]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [23]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [24]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [25]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [26]:
# arr1의 제곱근 구하기 
arr1 ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [27]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [28]:
arr3 = 1/arr1
arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

## Data Handling
-numpy의 제일 중요한 것은 indexing이다 (python의 List  와 흡사)


In [29]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# index 가 5인 data 불러오기 
arr[5]

5

In [32]:
# Slicing :
arr[5:9]

array([5, 6, 7, 8])

In [33]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [34]:
# arr의 처음부터 4번째 데이터 불러오기 

In [35]:
#arr의 처음부터 4번째 까지
arr[:5]

array([0, 1, 2, 3, 4])

In [36]:
# arr의 8번째 부터 끝까지 
arr[8:]

array([8, 9])

## 2차원

In [61]:
arr2d = np.array(
  [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
  ]
)

arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [39]:
# 2번행의 자료를 불러오기 
arr2d[2,:]

array([ 9, 10, 11, 12])

In [40]:
# 1에서 2번행의 자료 출력
arr2d[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
# 3번 열의 자료 출력 
arr2d[:,3]

array([ 4,  8, 12, 16])

In [42]:
# 0~1열의 자료출력 
arr2d[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [64]:
arr2d[0:2,1:3] = 0 
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Numpy의 함수 사용하기

In [65]:
# 1부터 9까지의  array 만들기
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

### 난수 발생하기

In [72]:
np.random.seed(0)   # 난수고정 ( 수업시만 필요 )
x = np.random.rand(8)
y = np.random.rand(8)
y

array([0.96366276, 0.38344152, 0.79172504, 0.52889492, 0.56804456,
       0.92559664, 0.07103606, 0.0871293 ])

In [73]:
# x와 y의 array 값들중에 최대값으로 구성된 array 만들기 
np.maximum(x,y)

array([0.96366276, 0.71518937, 0.79172504, 0.54488318, 0.56804456,
       0.92559664, 0.43758721, 0.891773  ])

In [75]:
# 전체 합 구하기 
print(x.sum())
print(np.sum(x))

4.810558553818618
4.810558553818618


In [77]:
# 평균 구하기 
print(x.mean())
print(np.mean(x))

0.6013198192273272
0.6013198192273272


In [78]:
arr = np.random.rand(5,4)
arr

array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 , 0.6176355 ]])

In [80]:
# arr의 열별로 합계 구하기 
print(arr.sum(axis=0))
print(np.sum(arr, axis=0))


[2.09510982 3.25479532 1.66633481 3.98707943]
[2.09510982 3.25479532 1.66633481 3.98707943]


In [82]:
# arr의 행별로 합 구하기 
print(arr.sum(axis=1))
print(np.sum(arr, axis=1))

[2.50100714 3.01978544 1.84621765 1.97529956 1.66100958]
[2.50100714 3.01978544 1.84621765 1.97529956 1.66100958]


In [84]:
# arr  중 데이터가 0.3 보다 큰수의 계산 
(arr > 0.3).sum()

15